server:
  port: 8040
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: m-gateway-zuul
  cloud:
    config:
      uri: http://localhost:7001/
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: usersServiceId

ribbon:
  eureka:
    enabled: false

usersServiceId:   #负载均衡
  ribbon:
    listOfServers: http://localhost:7001,http://localhost:7000