server:
  port: 8020
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: cloud-demo-order-consumer-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka