server:
  port: 5556
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: api-gateway-dynamic-route-zuul
  cloud:
    config:
      uri: http://localhost:7001/
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka