server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    #    由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    #    由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: false
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    prefer-ip-address: true
    instance-id: :${spring.application.name}:${spring.application.instance_id:${server.port}
    metadata-map:
      zone: ABC
      dongyl: BBC
security:
  user:
    name: user
    password: password
management:
  context-path: /admin
#endpoints:
#  info:
#    path: /appInfo
#  health:
#    path: /checkHealth
spring:
  application:
    name: discovery-eureka
    instance_id: