server:
  port: 5555
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: api-gateway-dynamic-filter-zuul
  cloud:
    config:
      uri: http://localhost:7001/
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
zuul:
  routes:
    movie:
      path: /movie-service/**
      serviceId: movie-servie
  #动态配置参数
  filter:
    #动态加载的过滤器存储路径
    root: filter
    #动态加载的间隔时间，单位秒
    interval: 5