server:
  port: 7900
spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/project_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: cloud-demo-user-provider
    instance_id:
  cloud:
    loadbalancer:
      retry:
        enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}
    metadata-map:
      # zone eureka 可以理解行为 会影响客户端
      #自定义不会影响
      zone:ABC
    #参数用于定义服务续约任务的调用间隔时间，默认为30秒。心跳 线上禁用
    lease-renewal-interval-in-seconds: 5
    #参数用于定义服务失效的时间，默认为90秒
    lease-expiration-duration-in-seconds: 90
#其中 hello-service 为服务名
#NFLoadBalancerPingClassName 参数用来指定具体的 IPing 接口实现类。
#在 Camden 版本中，Spring Cloud Ribbon 新增了一个org.springframework.cloud.netflix.ribbon.PropertiesFactory类来动态地为RibbonClient创建这些接口实现。
#user-service:
#  ribbon:
#    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl