package com.cloud.order.mapper;

import com.cloud.order.bean.po.EntityShareInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EntityShareInfoMapper {


    /**
     * 根据主键集合查询商品分享要素
     * @param ids
     * @return
     */
    List<EntityShareInfo> getShareInfoByIds(@Param("list") List<Long> ids);





//------------
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int countByExample(ShareInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int deleteByExample(ShareInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int insert(ShareInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int insertSelective(ShareInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    List<ShareInfo> selectByExample(ShareInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    ShareInfo selectByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int updateByExampleSelective(@Param("record") ShareInfo record, @Param("example") ShareInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int updateByExample(@Param("record") ShareInfo record, @Param("example") ShareInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(ShareInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table share_info
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(ShareInfo record);
//
//    /**
//     * 按商品Id集合，存储类型查询商品分享要素
//     * @param goodIds
//     * @param type
//     * @return
//     */
//    List<ShareInfo> selectByGoodidsAndType(@Param("goodIds") List<String> goodIds, @Param("cuType") String type);
//
//    /**
//     *批量插入发货单主表信息
//     * @param list
//     */
//    int batchSaveShareInfo(List<ShareInfo> list);
}