server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
security:
  user:
    name: user
    password: password

