server:
  port: 8030
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: movie-consumer-feign

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
feign:
  #压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true