server:
  port: 8010
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.cloud: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
spring:
  zipkin:
    base-url: http://localhost:9411