server:
  port: 7001
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: config-server
  cloud:
    config:
      uri: http://git.oschina.net/didispace/SpringCloud-Learning/
      server:
        git:
        searchPaths: spring_cloud_in_action/config-repo
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka