server:
  port: 9101
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.noriental: DEBUG
spring:
  application:
    name: tarce-svr-1
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka